"""PostgreSQL-backed storage for the published lookup + draft, used in
production when DATABASE_URL is set (see app.py's _USE_DB switch).

Shares vendor_lookups/db.py's connection pool (one pool per process,
regardless of how many schemas are in use) but keeps its own schema/DDL --
that module's ensure_schema() is hardwired to the vendor-cache tables
(metadata/products/releases), which are unrelated to this domain's
rows/evidence/meta/backups tables.

Row identity mirrors the CSV: keyed by (source, row_order), not os_string,
since real data has duplicate os_strings (the same reason
lookup_extras.merge_lookup_rows never dict-keys by os_string either) -- this
preserves the file format's ordered-list semantics exactly.

Every public function takes an optional `schema` override (default the real
"lookup" schema) so tests can point at a disposable per-test schema, the
same idiom tests/test_layer23_switch.py already uses for the vendor caches.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from datetime import datetime
from typing import Any

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict

from vendor_lookups.db import get_database_url, get_pool

SCHEMA = "lookup"

_DDL = """
CREATE TABLE IF NOT EXISTS rows (
    source TEXT NOT NULL,
    row_order INTEGER NOT NULL,
    os_string TEXT NOT NULL DEFAULT '',
    normalized_os_detailed_name TEXT NOT NULL DEFAULT '',
    normalized_os TEXT NOT NULL DEFAULT '',
    eol_date TEXT NOT NULL DEFAULT '',
    eol_status TEXT NOT NULL DEFAULT '',
    eoas_date TEXT NOT NULL DEFAULT '',
    eoas_status TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (source, row_order)
);
CREATE INDEX IF NOT EXISTS idx_lookup_rows_source_os ON rows (source, os_string);

CREATE TABLE IF NOT EXISTS evidence (
    source TEXT PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    suffix TEXT NOT NULL DEFAULT '',
    rows_json JSONB NOT NULL,
    evidence_json JSONB NOT NULL
);
"""

_ensured_schemas: set[str] = set()


class PublishConflictError(Exception):
    """Data has been published again since the draft's expected_revision."""

    def __init__(self, current_revision: int):
        self.current_revision = current_revision
        super().__init__(
            f"Data was published again since your draft started (now at revision {current_revision})."
        )


def ensure_schema(schema: str = SCHEMA) -> None:
    """Create this schema + its tables once per process (idempotent)."""
    if schema in _ensured_schemas:
        return
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))
        connection.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
        connection.execute(_DDL)
        connection.commit()
    _ensured_schemas.add(schema)


@contextmanager
def _connect(schema: str = SCHEMA) -> Iterator[psycopg.Connection[Any]]:
    ensure_schema(schema)
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise


def _get_meta(connection: psycopg.Connection[Any], key: str, default: str = "0") -> str:
    # The pool shared with vendor_lookups/db.py is configured with
    # row_factory=dict_row, so every result here is a dict keyed by column
    # name, not a positional tuple -- easy to get wrong (see the row-shape
    # bugs this comment replaced), so every access below is by column name.
    row = connection.execute("SELECT value FROM meta WHERE key = %s", (key,)).fetchone()
    return row["value"] if row else default


def _set_meta(connection: psycopg.Connection[Any], key: str, value: str) -> None:
    connection.execute(
        "INSERT INTO meta (key, value) VALUES (%s, %s) "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
        (key, value),
    )


def _data_revision(connection: psycopg.Connection[Any]) -> int:
    return int(_get_meta(connection, "data_revision", "0"))


def db_data_revision(schema: str = SCHEMA) -> int:
    with _connect(schema) as connection:
        return _data_revision(connection)


def db_draft_based_on_revision(schema: str = SCHEMA) -> int:
    with _connect(schema) as connection:
        return int(_get_meta(connection, "draft_based_on_revision", "0"))


def _row_tuple(source: str, index: int, row: dict[str, object]) -> tuple:
    return (
        source,
        index,
        str(row.get("os_string", "") or ""),
        str(row.get("normalized_os_detailed_name", "") or ""),
        str(row.get("normalized_os", "") or ""),
        str(row.get("eol_date", "") or ""),
        str(row.get("eol_status", "") or ""),
        str(row.get("eoas_date", "") or ""),
        str(row.get("eoas_status", "") or ""),
    )


def _insert_rows(
    connection: psycopg.Connection[Any],
    source: str,
    rows: list[dict[str, object]],
    on_progress: Callable[[int, int], None] | None = None,
) -> None:
    total = len(rows)
    for index, row in enumerate(rows):
        connection.execute(
            "INSERT INTO rows (source, row_order, os_string, normalized_os_detailed_name, "
            "normalized_os, eol_date, eol_status, eoas_date, eoas_status) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
            _row_tuple(source, index, row),
        )
        # One INSERT per row means one network round trip per row -- against
        # a remote Postgres (e.g. Aiven) that's the slow part by far, so this
        # is opt-in (only the CLI import passes on_progress) rather than
        # printing on every normal app request that saves rows.
        if on_progress and ((index + 1) % 250 == 0 or index + 1 == total):
            on_progress(index + 1, total)


def db_source_exists(source: str, schema: str = SCHEMA) -> bool:
    """Cheap existence check (mirrors DATA_PATH.exists()/DRAFT_PATH.exists()
    in file mode) -- a source "exists" once it has at least one row."""
    with _connect(schema) as connection:
        row = connection.execute("SELECT 1 FROM rows WHERE source = %s LIMIT 1", (source,)).fetchone()
        return row is not None


def db_load_rows(source: str, schema: str = SCHEMA) -> list[dict[str, str]]:
    with _connect(schema) as connection:
        cursor = connection.execute(
            "SELECT os_string, normalized_os_detailed_name, normalized_os, "
            "eol_date, eol_status, eoas_date, eoas_status "
            "FROM rows WHERE source = %s ORDER BY row_order",
            (source,),
        )
        return [dict(row) for row in cursor.fetchall()]


def db_save_rows(
    rows: list[dict[str, object]],
    source: str,
    schema: str = SCHEMA,
    on_progress: Callable[[int, int], None] | None = None,
) -> None:
    """Delete+bulk-insert for this source in one transaction. Stamps
    draft_based_on_revision the first time draft rows are written for a
    fresh draft (the DB-mode equivalent of file mode's base-snapshot
    capture -- just a revision number here, since DB mode's publish only
    needs a "has anything changed" guard, not a full row-level merge)."""
    with _connect(schema) as connection:
        if source == "draft":
            existing = connection.execute("SELECT 1 FROM rows WHERE source = 'draft' LIMIT 1").fetchone()
            if existing is None:
                _set_meta(connection, "draft_based_on_revision", str(_data_revision(connection)))
        connection.execute("DELETE FROM rows WHERE source = %s", (source,))
        _insert_rows(connection, source, rows, on_progress=on_progress)


def db_load_evidence(source: str, schema: str = SCHEMA) -> dict[str, object]:
    with _connect(schema) as connection:
        row = connection.execute(
            "SELECT payload, updated_at FROM evidence WHERE source = %s", (source,)
        ).fetchone()
        if not row:
            return {"by_os": {}, "updated_at": ""}
        payload = row["payload"]
        by_os = payload.get("by_os") if isinstance(payload, dict) else None
        return {"by_os": by_os if isinstance(by_os, dict) else {}, "updated_at": row["updated_at"] or ""}


def _normalize_evidence(evidence: object) -> dict[str, object]:
    by_os = evidence.get("by_os") if isinstance(evidence, dict) else None
    updated_at = str(evidence.get("updated_at") or "") if isinstance(evidence, dict) else ""
    if not updated_at:
        updated_at = datetime.now().isoformat(timespec="seconds")
    return {"by_os": by_os if isinstance(by_os, dict) else {}, "updated_at": updated_at}


def db_save_evidence(evidence: dict[str, object], source: str, schema: str = SCHEMA) -> dict[str, object]:
    normalized = _normalize_evidence(evidence)
    with _connect(schema) as connection:
        connection.execute(
            "INSERT INTO evidence (source, payload, updated_at) VALUES (%s, %s::jsonb, %s) "
            "ON CONFLICT (source) DO UPDATE SET payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (source, json.dumps(normalized), normalized["updated_at"]),
        )
    return normalized


def db_delete_draft(schema: str = SCHEMA) -> None:
    with _connect(schema) as connection:
        connection.execute("DELETE FROM rows WHERE source = 'draft'")
        connection.execute("DELETE FROM evidence WHERE source = 'draft'")
        connection.execute("DELETE FROM meta WHERE key = 'draft_based_on_revision'")


def db_publish(
    resolved_rows: list[dict[str, object]],
    resolved_evidence: dict[str, object],
    expected_revision: int,
    backup_suffix: str = "",
    schema: str = SCHEMA,
) -> dict[str, object]:
    """Transactional publish with an optimistic-concurrency guard: refuses
    to overwrite Data if it was published again since expected_revision.

    An advisory lock serializes every publish attempt (held only for the
    duration of this transaction, released automatically on commit/
    rollback) -- without it, two concurrent transactions under Postgres's
    default READ COMMITTED isolation could both read the same
    pre-publish revision and both believe they're clear to write. Publishes
    are rare, human-triggered events, so serializing them fully is the
    simplest correct answer; it doesn't affect read throughput at all.
    """
    with _connect(schema) as connection:
        connection.execute("SELECT pg_advisory_xact_lock(hashtext('oshealth_lookup_publish'))")
        current_revision = _data_revision(connection)
        if current_revision != expected_revision:
            raise PublishConflictError(current_revision)

        current_rows = connection.execute(
            "SELECT os_string, normalized_os_detailed_name, normalized_os, "
            "eol_date, eol_status, eoas_date, eoas_status "
            "FROM rows WHERE source = 'data' ORDER BY row_order"
        ).fetchall()
        current_evidence_row = connection.execute(
            "SELECT payload FROM evidence WHERE source = 'data'"
        ).fetchone()
        current_evidence = current_evidence_row["payload"] if current_evidence_row else {"by_os": {}, "updated_at": ""}
        created_at = datetime.now().isoformat(timespec="seconds")
        connection.execute(
            "INSERT INTO backups (created_at, suffix, rows_json, evidence_json) "
            "VALUES (%s, %s, %s::jsonb, %s::jsonb)",
            (
                created_at,
                backup_suffix,
                json.dumps([dict(row) for row in current_rows]),
                json.dumps(current_evidence),
            ),
        )

        connection.execute("DELETE FROM rows WHERE source = 'data'")
        _insert_rows(connection, "data", resolved_rows)

        normalized_evidence = _normalize_evidence(resolved_evidence)
        normalized_evidence["updated_at"] = created_at
        connection.execute(
            "INSERT INTO evidence (source, payload, updated_at) VALUES ('data', %s::jsonb, %s) "
            "ON CONFLICT (source) DO UPDATE SET payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (json.dumps(normalized_evidence), created_at),
        )

        connection.execute("DELETE FROM rows WHERE source = 'draft'")
        connection.execute("DELETE FROM evidence WHERE source = 'draft'")
        connection.execute("DELETE FROM meta WHERE key = 'draft_based_on_revision'")

        new_revision = current_revision + 1
        _set_meta(connection, "data_revision", str(new_revision))
        _set_meta(connection, "published_at", created_at)

        return {"data_revision": new_revision, "evidence": normalized_evidence, "row_count": len(resolved_rows)}


def db_published_at(schema: str = SCHEMA) -> str:
    with _connect(schema) as connection:
        return _get_meta(connection, "published_at", "")


def describe_target() -> str:
    """host:port/dbname parsed from DATABASE_URL, never the password -- safe
    to show in the CLI import output or the app's storage-mode indicator."""
    try:
        info = conninfo_to_dict(get_database_url())
        return f"{info.get('host', '?')}:{info.get('port', '5432')}/{info.get('dbname', '?')}"
    except Exception:
        return "Postgres"


def _import_from_files() -> None:
    """One-time migration: loads the current file-mode _data/eol_lookup.csv
    + evidence sidecar into this DB's 'data' source, for cutting a real
    deployment over from file-mode to DB-mode without losing what's already
    published. Run directly: `python lookup_db.py`."""
    import time

    import app  # local import -- avoids a circular import when app.py imports this module

    if app._USE_DB:
        # app.load_rows("data") below would silently read from (likely empty)
        # Postgres instead of the local CSV if LOOKUP_DB_ENABLED is already
        # on -- exactly how a prior run of this script quietly "imported" 0
        # rows. Fail loudly instead of repeating that.
        raise SystemExit(
            "LOOKUP_DB_ENABLED is already set -- unset it (keep DATABASE_URL), "
            "rerun this script so it reads the local CSV instead of Postgres, "
            "then set LOOKUP_DB_ENABLED=true again afterward."
        )

    target = describe_target()
    print(f"Connecting to {target} ...")
    t0 = time.monotonic()
    try:
        with get_pool().connection() as connection:
            connection.execute("SELECT 1")
    except Exception as exc:
        print(f"Connection failed after {time.monotonic() - t0:.2f}s: {exc}")
        raise
    print(f"Connected in {time.monotonic() - t0:.2f}s.")

    rows = app.load_rows("data") if app.DATA_PATH.exists() else []
    evidence = app.load_evidence("data")

    print(f"Importing {len(rows)} row(s) into schema '{SCHEMA}' at {target} ...")

    def report(done: int, total: int) -> None:
        print(f"  {done}/{total} row(s) inserted ({done * 100 // total if total else 100}%)")

    db_save_rows(rows, "data", on_progress=report)
    db_save_evidence(evidence, "data")
    print(f"Imported {len(rows)} row(s) into Postgres schema '{SCHEMA}'.")


if __name__ == "__main__":
    _import_from_files()
