"""PostgreSQL-backed storage for the published lookup + draft -- the only
storage backend app.py supports (see its startup check for DATABASE_URL /
LOOKUP_DB_ENABLED).

Shares vendor_lookups/db.py's connection pool (one pool per process,
regardless of how many schemas are in use) but keeps its own schema/DDL --
that module's ensure_schema() is hardwired to the vendor-cache tables
(metadata/products/releases), which are unrelated to this domain's
rows/evidence/meta/backups tables.

Row identity mirrors the CSV: keyed by (source, row_order), not os_string,
since real data has duplicate os_strings -- this preserves the file
format's ordered-list semantics exactly.

Every public function takes an optional `schema` override (default the real
"lookup" schema) so tests can point at a disposable per-test schema, the
same idiom tests/test_layer23_switch.py already uses for the vendor caches.
"""

from __future__ import annotations

import json
import secrets
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from datetime import datetime
from typing import Any

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict

from vendor_lookups.db import get_database_url, get_pool

SCHEMA = "lookup"

_DDL = """
CREATE TABLE IF NOT EXISTS rows (
    source TEXT NOT NULL,
    row_order INTEGER NOT NULL,
    os_string TEXT NOT NULL DEFAULT '',
    normalized_os_detailed_name TEXT NOT NULL DEFAULT '',
    normalized_os TEXT NOT NULL DEFAULT '',
    eol_date TEXT NOT NULL DEFAULT '',
    eol_status TEXT NOT NULL DEFAULT '',
    eoas_date TEXT NOT NULL DEFAULT '',
    eoas_status TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (source, row_order)
);
CREATE INDEX IF NOT EXISTS idx_lookup_rows_source_os ON rows (source, os_string);

CREATE TABLE IF NOT EXISTS evidence (
    source TEXT PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    suffix TEXT NOT NULL DEFAULT '',
    rows_json JSONB NOT NULL,
    evidence_json JSONB NOT NULL
);

-- Per-user Draft (docs/AUTH_MULTITENANCY_PLAN.md §6) -- replaces the old
-- single-global-draft rows in `rows`/`evidence` (source = 'draft'), which
-- migrate_legacy_global_draft_if_present() below retires. `data` keeps using
-- the `rows`/`evidence` tables above unchanged -- published Data stays one
-- shared dataset per the plan's decision, only Draft becomes per-user.
-- owner_user_id is this app's own iam.users.id (a UUID string), never the
-- raw Keycloak `sub` -- see iam_db.py.
CREATE TABLE IF NOT EXISTS draft_rows (
    deployment_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    row_order INTEGER NOT NULL,
    os_string TEXT NOT NULL DEFAULT '',
    normalized_os_detailed_name TEXT NOT NULL DEFAULT '',
    normalized_os TEXT NOT NULL DEFAULT '',
    eol_date TEXT NOT NULL DEFAULT '',
    eol_status TEXT NOT NULL DEFAULT '',
    eoas_date TEXT NOT NULL DEFAULT '',
    eoas_status TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (deployment_id, owner_user_id, row_order)
);

CREATE TABLE IF NOT EXISTS draft_evidence (
    deployment_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    payload JSONB NOT NULL,
    updated_at TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (deployment_id, owner_user_id)
);

-- Per-user replacement for the old global meta.draft_based_on_revision --
-- "which Data revision was my draft based on" is now a per-user fact.
CREATE TABLE IF NOT EXISTS draft_meta (
    deployment_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    based_on_revision INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (deployment_id, owner_user_id)
);
"""

# Column added after backups' initial release -- ALTER .. ADD COLUMN IF NOT
# EXISTS, run unconditionally in ensure_schema, is the idempotent-migration
# idiom for a column added to an already-existing table (CREATE TABLE IF NOT
# EXISTS above only ever helps on a brand-new table).
_BACKUPS_PUBLISHED_BY_COLUMN_DDL = (
    "ALTER TABLE backups ADD COLUMN IF NOT EXISTS published_by_user_id TEXT NOT NULL DEFAULT '';"
)

_ensured_schemas: set[str] = set()

# Cross-instance vendor-sync lock, stored as meta rows so every app instance
# sharing this database (not just this process) sees whether a sync is
# running -- see db_acquire_sync_lock.
_SYNC_LOCK_HOLDER_KEY = "sync_lock_holder"
_SYNC_LOCK_LABEL_KEY = "sync_lock_label"
_SYNC_LOCK_HEARTBEAT_KEY = "sync_lock_heartbeat_at"

# A holder must refresh its heartbeat more often than this (see app.py's
# _SYNC_LOCK_HEARTBEAT_INTERVAL_SECONDS) or the lock is treated as abandoned
# (its holding process crashed/was killed) and another instance may steal it.
_SYNC_LOCK_STALE_AFTER_SECONDS = 180


class PublishConflictError(Exception):
    """Data has been published again since the draft's expected_revision."""

    def __init__(self, current_revision: int):
        self.current_revision = current_revision
        super().__init__(
            f"Data was published again since your draft started (now at revision {current_revision})."
        )


def ensure_schema(schema: str = SCHEMA) -> None:
    """Create this schema + its tables once per process (idempotent)."""
    if schema in _ensured_schemas:
        return
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))
        connection.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
        connection.execute(_DDL)
        connection.execute(_BACKUPS_PUBLISHED_BY_COLUMN_DDL)
        # The sync lock's holder row must already exist before its first use
        # -- SELECT ... FOR UPDATE can't lock a row that isn't there yet, and
        # without this, two instances' very first acquire attempt could race.
        connection.execute(
            "INSERT INTO meta (key, value) VALUES (%s, '') ON CONFLICT (key) DO NOTHING",
            (_SYNC_LOCK_HOLDER_KEY,),
        )
        connection.commit()
    _ensured_schemas.add(schema)


@contextmanager
def _connect(schema: str = SCHEMA) -> Iterator[psycopg.Connection[Any]]:
    ensure_schema(schema)
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise


def _get_meta(connection: psycopg.Connection[Any], key: str, default: str = "0") -> str:
    # The pool shared with vendor_lookups/db.py is configured with
    # row_factory=dict_row, so every result here is a dict keyed by column
    # name, not a positional tuple -- easy to get wrong (see the row-shape
    # bugs this comment replaced), so every access below is by column name.
    row = connection.execute("SELECT value FROM meta WHERE key = %s", (key,)).fetchone()
    return row["value"] if row else default


def _set_meta(connection: psycopg.Connection[Any], key: str, value: str) -> None:
    connection.execute(
        "INSERT INTO meta (key, value) VALUES (%s, %s) "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
        (key, value),
    )


def _data_revision(connection: psycopg.Connection[Any]) -> int:
    return int(_get_meta(connection, "data_revision", "0"))


def db_data_revision(schema: str = SCHEMA) -> int:
    with _connect(schema) as connection:
        return _data_revision(connection)


def db_draft_based_on_revision(deployment_id: str, owner_user_id: str, schema: str = SCHEMA) -> int:
    with _connect(schema) as connection:
        return _conn_draft_based_on_revision(connection, deployment_id, owner_user_id)

# Chunk size for executemany inserts -- keeps progress callbacks useful on
# large imports while still collapsing thousands of remote round-trips into
# a handful of batched statements (critical against Azure Flexible Server /
# RDS at 5k–20k rows).
_INSERT_CHUNK = 500

_ROWS_SELECT = (
    "SELECT os_string, normalized_os_detailed_name, normalized_os, "
    "eol_date, eol_status, eoas_date, eoas_status "
)


def _row_tuple(source: str, index: int, row: dict[str, object]) -> tuple:
    return (
        source,
        index,
        str(row.get("os_string", "") or ""),
        str(row.get("normalized_os_detailed_name", "") or ""),
        str(row.get("normalized_os", "") or ""),
        str(row.get("eol_date", "") or ""),
        str(row.get("eol_status", "") or ""),
        str(row.get("eoas_date", "") or ""),
        str(row.get("eoas_status", "") or ""),
    )


def _insert_rows(
    connection: psycopg.Connection[Any],
    source: str,
    rows: list[dict[str, object]],
    on_progress: Callable[[int, int], None] | None = None,
) -> None:
    """Bulk-insert published `rows` via cursor.executemany (chunked). Far
    fewer network round-trips than one INSERT per row against remote Postgres.
    (psycopg Connection has .execute but not .executemany -- use a cursor.)"""
    total = len(rows)
    if total == 0:
        return
    query = (
        "INSERT INTO rows (source, row_order, os_string, normalized_os_detailed_name, "
        "normalized_os, eol_date, eol_status, eoas_date, eoas_status) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
    )
    with connection.cursor() as cur:
        for start in range(0, total, _INSERT_CHUNK):
            chunk = rows[start : start + _INSERT_CHUNK]
            cur.executemany(
                query,
                [_row_tuple(source, start + index, row) for index, row in enumerate(chunk)],
            )
            if on_progress:
                on_progress(min(start + len(chunk), total), total)


def _conn_load_rows(connection: psycopg.Connection[Any], source: str) -> list[dict[str, str]]:
    cursor = connection.execute(
        _ROWS_SELECT + "FROM rows WHERE source = %s ORDER BY row_order",
        (source,),
    )
    return [dict(row) for row in cursor.fetchall()]


def _conn_load_evidence(connection: psycopg.Connection[Any], source: str) -> dict[str, object]:
    row = connection.execute(
        "SELECT payload, updated_at FROM evidence WHERE source = %s", (source,)
    ).fetchone()
    if not row:
        return {"by_os": {}, "updated_at": ""}
    payload = row["payload"]
    by_os = payload.get("by_os") if isinstance(payload, dict) else None
    return {"by_os": by_os if isinstance(by_os, dict) else {}, "updated_at": row["updated_at"] or ""}


def _conn_draft_exists(
    connection: psycopg.Connection[Any], deployment_id: str, owner_user_id: str
) -> bool:
    row = connection.execute(
        "SELECT 1 FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s LIMIT 1",
        (deployment_id, owner_user_id),
    ).fetchone()
    return row is not None


def _conn_load_draft_rows(
    connection: psycopg.Connection[Any], deployment_id: str, owner_user_id: str
) -> list[dict[str, str]]:
    cursor = connection.execute(
        _ROWS_SELECT
        + "FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s ORDER BY row_order",
        (deployment_id, owner_user_id),
    )
    return [dict(row) for row in cursor.fetchall()]


def _conn_load_draft_evidence(
    connection: psycopg.Connection[Any], deployment_id: str, owner_user_id: str
) -> dict[str, object]:
    row = connection.execute(
        "SELECT payload, updated_at FROM draft_evidence WHERE deployment_id = %s AND owner_user_id = %s",
        (deployment_id, owner_user_id),
    ).fetchone()
    if not row:
        return {"by_os": {}, "updated_at": ""}
    payload = row["payload"]
    by_os = payload.get("by_os") if isinstance(payload, dict) else None
    return {"by_os": by_os if isinstance(by_os, dict) else {}, "updated_at": row["updated_at"] or ""}


def _conn_draft_based_on_revision(
    connection: psycopg.Connection[Any], deployment_id: str, owner_user_id: str
) -> int:
    row = connection.execute(
        "SELECT based_on_revision FROM draft_meta WHERE deployment_id = %s AND owner_user_id = %s",
        (deployment_id, owner_user_id),
    ).fetchone()
    return int(row["based_on_revision"]) if row else 0


def db_source_exists(source: str, schema: str = SCHEMA) -> bool:
    """Cheap existence check -- a source "exists" once it has at least one row."""
    with _connect(schema) as connection:
        row = connection.execute("SELECT 1 FROM rows WHERE source = %s LIMIT 1", (source,)).fetchone()
        return row is not None


def db_load_rows(source: str, schema: str = SCHEMA) -> list[dict[str, str]]:
    with _connect(schema) as connection:
        return _conn_load_rows(connection, source)


def db_save_rows(
    rows: list[dict[str, object]],
    source: str,
    schema: str = SCHEMA,
    on_progress: Callable[[int, int], None] | None = None,
) -> None:
    """Delete+bulk-insert for this source in one transaction. Only ever
    called with source='data' now -- Draft moved to its own per-user tables
    (db_save_draft_rows below); see docs/AUTH_MULTITENANCY_PLAN.md §6."""
    with _connect(schema) as connection:
        connection.execute("DELETE FROM rows WHERE source = %s", (source,))
        _insert_rows(connection, source, rows, on_progress=on_progress)


def db_load_evidence(source: str, schema: str = SCHEMA) -> dict[str, object]:
    with _connect(schema) as connection:
        return _conn_load_evidence(connection, source)

def _normalize_evidence(evidence: object) -> dict[str, object]:
    by_os = evidence.get("by_os") if isinstance(evidence, dict) else None
    updated_at = str(evidence.get("updated_at") or "") if isinstance(evidence, dict) else ""
    if not updated_at:
        updated_at = datetime.now().isoformat(timespec="seconds")
    return {"by_os": by_os if isinstance(by_os, dict) else {}, "updated_at": updated_at}


def db_save_evidence(evidence: dict[str, object], source: str, schema: str = SCHEMA) -> dict[str, object]:
    normalized = _normalize_evidence(evidence)
    with _connect(schema) as connection:
        connection.execute(
            "INSERT INTO evidence (source, payload, updated_at) VALUES (%s, %s::jsonb, %s) "
            "ON CONFLICT (source) DO UPDATE SET payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (source, json.dumps(normalized), normalized["updated_at"]),
        )
    return normalized


def _draft_row_tuple(deployment_id: str, owner_user_id: str, index: int, row: dict[str, object]) -> tuple:
    return (
        deployment_id,
        owner_user_id,
        index,
        str(row.get("os_string", "") or ""),
        str(row.get("normalized_os_detailed_name", "") or ""),
        str(row.get("normalized_os", "") or ""),
        str(row.get("eol_date", "") or ""),
        str(row.get("eol_status", "") or ""),
        str(row.get("eoas_date", "") or ""),
        str(row.get("eoas_status", "") or ""),
    )


def _insert_draft_rows(
    connection: psycopg.Connection[Any],
    deployment_id: str,
    owner_user_id: str,
    rows: list[dict[str, object]],
) -> None:
    total = len(rows)
    if total == 0:
        return
    query = (
        "INSERT INTO draft_rows (deployment_id, owner_user_id, row_order, os_string, "
        "normalized_os_detailed_name, normalized_os, eol_date, eol_status, eoas_date, eoas_status) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
    )
    with connection.cursor() as cur:
        for start in range(0, total, _INSERT_CHUNK):
            chunk = rows[start : start + _INSERT_CHUNK]
            cur.executemany(
                query,
                [
                    _draft_row_tuple(deployment_id, owner_user_id, start + index, row)
                    for index, row in enumerate(chunk)
                ],
            )


def db_draft_exists(deployment_id: str, owner_user_id: str, schema: str = SCHEMA) -> bool:
    """Cheap existence check for one user's private draft -- "exists" once
    it has at least one row, same convention as db_source_exists("data")."""
    with _connect(schema) as connection:
        return _conn_draft_exists(connection, deployment_id, owner_user_id)


def db_load_draft_rows(deployment_id: str, owner_user_id: str, schema: str = SCHEMA) -> list[dict[str, str]]:
    with _connect(schema) as connection:
        return _conn_load_draft_rows(connection, deployment_id, owner_user_id)


def db_save_draft_rows(
    rows: list[dict[str, object]],
    deployment_id: str,
    owner_user_id: str,
    schema: str = SCHEMA,
) -> None:
    """Delete+bulk-insert this user's draft rows in one transaction. Stamps
    draft_meta.based_on_revision the first time this user's draft is written
    for a fresh draft -- same "has anything changed" guard db_save_rows'
    old draft branch used to do, just per-user now."""
    with _connect(schema) as connection:
        existing = connection.execute(
            "SELECT 1 FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s LIMIT 1",
            (deployment_id, owner_user_id),
        ).fetchone()
        if existing is None:
            connection.execute(
                "INSERT INTO draft_meta (deployment_id, owner_user_id, based_on_revision, updated_at) "
                "VALUES (%s, %s, %s, %s) "
                "ON CONFLICT (deployment_id, owner_user_id) DO UPDATE SET "
                "based_on_revision = EXCLUDED.based_on_revision, updated_at = EXCLUDED.updated_at",
                (deployment_id, owner_user_id, _data_revision(connection), datetime.now().isoformat(timespec="seconds")),
            )
        connection.execute(
            "DELETE FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s",
            (deployment_id, owner_user_id),
        )
        _insert_draft_rows(connection, deployment_id, owner_user_id, rows)


def db_load_draft_evidence(deployment_id: str, owner_user_id: str, schema: str = SCHEMA) -> dict[str, object]:
    with _connect(schema) as connection:
        return _conn_load_draft_evidence(connection, deployment_id, owner_user_id)

def db_save_draft_evidence(
    evidence: dict[str, object], deployment_id: str, owner_user_id: str, schema: str = SCHEMA
) -> dict[str, object]:
    normalized = _normalize_evidence(evidence)
    with _connect(schema) as connection:
        connection.execute(
            "INSERT INTO draft_evidence (deployment_id, owner_user_id, payload, updated_at) "
            "VALUES (%s, %s, %s::jsonb, %s) "
            "ON CONFLICT (deployment_id, owner_user_id) DO UPDATE SET "
            "payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (deployment_id, owner_user_id, json.dumps(normalized), normalized["updated_at"]),
        )
    return normalized


def db_delete_draft(deployment_id: str, owner_user_id: str, schema: str = SCHEMA) -> None:
    with _connect(schema) as connection:
        connection.execute(
            "DELETE FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s", (deployment_id, owner_user_id)
        )
        connection.execute(
            "DELETE FROM draft_evidence WHERE deployment_id = %s AND owner_user_id = %s",
            (deployment_id, owner_user_id),
        )
        connection.execute(
            "DELETE FROM draft_meta WHERE deployment_id = %s AND owner_user_id = %s", (deployment_id, owner_user_id)
        )


def migrate_legacy_global_draft_if_present(schema: str = SCHEMA) -> bool:
    """One-time cutover (docs/AUTH_MULTITENANCY_PLAN.md §9): before per-user
    drafts existed, there was exactly one shared global draft in
    rows/evidence (source='draft'). It has no owner, so it cannot be
    mechanically assigned to "the right" user -- this snapshots it into
    backups (so nothing is silently lost) and then drops it, so a fresh
    per-user draft starts clean. Safe to call on every startup: a no-op
    once the legacy rows are gone. Whoever owned that deployment's
    in-progress draft should be told, before this runs, to either publish
    it or note its state -- see the plan's operational checklist."""
    with _connect(schema) as connection:
        existing = connection.execute("SELECT 1 FROM rows WHERE source = 'draft' LIMIT 1").fetchone()
        if existing is None:
            return False

        legacy_rows = connection.execute(
            "SELECT os_string, normalized_os_detailed_name, normalized_os, "
            "eol_date, eol_status, eoas_date, eoas_status "
            "FROM rows WHERE source = 'draft' ORDER BY row_order"
        ).fetchall()
        evidence_row = connection.execute("SELECT payload FROM evidence WHERE source = 'draft'").fetchone()
        legacy_evidence = evidence_row["payload"] if evidence_row else {"by_os": {}, "updated_at": ""}

        created_at = datetime.now().isoformat(timespec="seconds")
        connection.execute(
            "INSERT INTO backups (created_at, suffix, rows_json, evidence_json) VALUES (%s, %s, %s::jsonb, %s::jsonb)",
            (
                created_at,
                "legacy-global-draft-migration",
                json.dumps([dict(row) for row in legacy_rows]),
                json.dumps(legacy_evidence),
            ),
        )
        connection.execute("DELETE FROM rows WHERE source = 'draft'")
        connection.execute("DELETE FROM evidence WHERE source = 'draft'")
        connection.execute("DELETE FROM meta WHERE key = 'draft_based_on_revision'")

    print(
        f"[lookup_db] Migrated legacy global draft ({len(legacy_rows)} row(s)) into "
        f"backups (suffix 'legacy-global-draft-migration') for schema '{schema}' -- "
        "per-user drafts start empty from here."
    )
    return True


def db_publish(
    resolved_rows: list[dict[str, object]],
    resolved_evidence: dict[str, object],
    expected_revision: int,
    deployment_id: str,
    owner_user_id: str,
    published_by_user_id: str = "",
    backup_suffix: str = "",
    schema: str = SCHEMA,
) -> dict[str, object]:
    """Transactional publish with an optimistic-concurrency guard: refuses
    to overwrite Data if it was published again since expected_revision.

    "Publish" now means *this specific user's* private draft
    (deployment_id, owner_user_id) overwrites the shared, still-global Data
    -- only that user's own draft is cleared afterward; every other user's
    in-progress draft in this deployment is untouched. published_by_user_id
    is normally the same as owner_user_id (a user publishing their own
    draft) but is recorded separately for audit (docs/AUTH_MULTITENANCY_PLAN.md
    §6.3) in case that ever changes.

    An advisory lock serializes every publish attempt (held only for the
    duration of this transaction, released automatically on commit/
    rollback) -- without it, two concurrent transactions under Postgres's
    default READ COMMITTED isolation could both read the same
    pre-publish revision and both believe they're clear to write. Publishes
    are rare, human-triggered events, so serializing them fully is the
    simplest correct answer; it doesn't affect read throughput at all.
    """
    with _connect(schema) as connection:
        connection.execute("SELECT pg_advisory_xact_lock(hashtext('oshealth_lookup_publish'))")
        current_revision = _data_revision(connection)
        if current_revision != expected_revision:
            raise PublishConflictError(current_revision)

        current_rows = connection.execute(
            "SELECT os_string, normalized_os_detailed_name, normalized_os, "
            "eol_date, eol_status, eoas_date, eoas_status "
            "FROM rows WHERE source = 'data' ORDER BY row_order"
        ).fetchall()
        current_evidence_row = connection.execute(
            "SELECT payload FROM evidence WHERE source = 'data'"
        ).fetchone()
        current_evidence = current_evidence_row["payload"] if current_evidence_row else {"by_os": {}, "updated_at": ""}
        created_at = datetime.now().isoformat(timespec="seconds")
        connection.execute(
            "INSERT INTO backups (created_at, suffix, rows_json, evidence_json, published_by_user_id) "
            "VALUES (%s, %s, %s::jsonb, %s::jsonb, %s)",
            (
                created_at,
                backup_suffix,
                json.dumps([dict(row) for row in current_rows]),
                json.dumps(current_evidence),
                published_by_user_id,
            ),
        )

        connection.execute("DELETE FROM rows WHERE source = 'data'")
        _insert_rows(connection, "data", resolved_rows)

        normalized_evidence = _normalize_evidence(resolved_evidence)
        normalized_evidence["updated_at"] = created_at
        connection.execute(
            "INSERT INTO evidence (source, payload, updated_at) VALUES ('data', %s::jsonb, %s) "
            "ON CONFLICT (source) DO UPDATE SET payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (json.dumps(normalized_evidence), created_at),
        )

        connection.execute(
            "DELETE FROM draft_rows WHERE deployment_id = %s AND owner_user_id = %s", (deployment_id, owner_user_id)
        )
        connection.execute(
            "DELETE FROM draft_evidence WHERE deployment_id = %s AND owner_user_id = %s",
            (deployment_id, owner_user_id),
        )
        connection.execute(
            "DELETE FROM draft_meta WHERE deployment_id = %s AND owner_user_id = %s", (deployment_id, owner_user_id)
        )

        new_revision = current_revision + 1
        _set_meta(connection, "data_revision", str(new_revision))
        _set_meta(connection, "published_at", created_at)
        _set_meta(connection, "published_by_user_id", published_by_user_id)

        return {"data_revision": new_revision, "evidence": normalized_evidence, "row_count": len(resolved_rows)}


def db_published_at(schema: str = SCHEMA) -> str:
    with _connect(schema) as connection:
        return _get_meta(connection, "published_at", "")


def db_fetch_lookup_view(
    source: str,
    deployment_id: str,
    owner_user_id: str,
    schema: str = SCHEMA,
) -> dict[str, object]:
    """Everything GET /api/lookup needs, in one Postgres transaction.

    Collapses the previous 5–7 separate connections (rows, evidence,
    published_at, draft_exists, data_revision, optional based_on_revision)
    into a single round-trip batch -- the dominant latency against remote
    Azure/RDS when the payload itself is small (empty draft).
    """
    normalized = source.strip().lower()
    with _connect(schema) as connection:
        if normalized == "draft":
            rows = _conn_load_draft_rows(connection, deployment_id, owner_user_id)
            evidence = _conn_load_draft_evidence(connection, deployment_id, owner_user_id)
            draft_exists = len(rows) > 0
        else:
            rows = _conn_load_rows(connection, "data")
            evidence = _conn_load_evidence(connection, "data")
            draft_exists = _conn_draft_exists(connection, deployment_id, owner_user_id)

        result: dict[str, object] = {
            "rows": rows,
            "evidence": evidence,
            "published_at": _get_meta(connection, "published_at", ""),
            "draft_exists": draft_exists,
            "data_revision": _data_revision(connection),
        }
        if normalized == "draft" and draft_exists:
            result["based_on_revision"] = _conn_draft_based_on_revision(
                connection, deployment_id, owner_user_id
            )
        return result


def db_fetch_diff_inputs(
    deployment_id: str,
    owner_user_id: str,
    schema: str = SCHEMA,
) -> dict[str, object] | None:
    """Rows needed for GET /api/lookup/diff in one transaction. Returns None
    when the user's draft does not exist (same empty-diff short-circuit as
    before)."""
    with _connect(schema) as connection:
        if not _conn_draft_exists(connection, deployment_id, owner_user_id):
            return None
        data_exists = (
            connection.execute("SELECT 1 FROM rows WHERE source = 'data' LIMIT 1").fetchone()
            is not None
        )
        return {
            "data_rows": _conn_load_rows(connection, "data") if data_exists else [],
            "draft_rows": _conn_load_draft_rows(connection, deployment_id, owner_user_id),
        }


def _sync_lock_is_stale(heartbeat_at: str) -> bool:
    if not heartbeat_at:
        return True
    try:
        age_seconds = (datetime.now() - datetime.fromisoformat(heartbeat_at)).total_seconds()
    except ValueError:
        return True
    return age_seconds > _SYNC_LOCK_STALE_AFTER_SECONDS


def db_acquire_sync_lock(label: str, schema: str = SCHEMA) -> str | None:
    """Cross-instance vendor-sync lock: with multiple app instances sharing
    one Postgres database, a plain in-process asyncio.Lock only protects
    the instance running the sync -- another instance has no idea it's
    happening, and can start its own sync (or an Add OS / Refresh EOL/EOAS,
    which read the exact vendor tables a sync deletes+reinserts into per
    product) at the same time, risking a torn/incomplete read.

    ``SELECT ... FOR UPDATE`` on the holder row serializes concurrent
    acquire attempts across instances -- the second transaction blocks
    until the first commits, then re-reads the now-current value, so only
    one instance can ever win a live lock. A heartbeat + staleness timeout
    (rather than relying on connection/session lifetime) recovers
    automatically if a holder process crashes mid-sync without releasing.

    Returns an opaque holder token (pass it to db_release_sync_lock /
    db_heartbeat_sync_lock), or None if another instance already holds a
    live (non-stale) lock.
    """
    with _connect(schema) as connection:
        row = connection.execute(
            "SELECT value FROM meta WHERE key = %s FOR UPDATE", (_SYNC_LOCK_HOLDER_KEY,)
        ).fetchone()
        current_holder = row["value"] if row else ""
        if current_holder and not _sync_lock_is_stale(_get_meta(connection, _SYNC_LOCK_HEARTBEAT_KEY, "")):
            return None

        holder = secrets.token_hex(16)
        _set_meta(connection, _SYNC_LOCK_HOLDER_KEY, holder)
        _set_meta(connection, _SYNC_LOCK_LABEL_KEY, label)
        _set_meta(connection, _SYNC_LOCK_HEARTBEAT_KEY, datetime.now().isoformat(timespec="seconds"))
        return holder


def db_heartbeat_sync_lock(holder: str, schema: str = SCHEMA) -> bool:
    """Refresh the lock's heartbeat while a sync is still running. Returns
    False if the lock was lost (another instance's staleness timeout fired
    and it took over) -- callers should treat that as a signal to stop."""
    with _connect(schema) as connection:
        row = connection.execute(
            "SELECT value FROM meta WHERE key = %s FOR UPDATE", (_SYNC_LOCK_HOLDER_KEY,)
        ).fetchone()
        if not row or row["value"] != holder:
            return False
        _set_meta(connection, _SYNC_LOCK_HEARTBEAT_KEY, datetime.now().isoformat(timespec="seconds"))
        return True


def db_release_sync_lock(holder: str, schema: str = SCHEMA) -> None:
    """Only clears the lock if ``holder`` still owns it -- a lock already
    stolen by another instance (after this holder went stale) must not be
    released out from under its new owner."""
    with _connect(schema) as connection:
        row = connection.execute(
            "SELECT value FROM meta WHERE key = %s FOR UPDATE", (_SYNC_LOCK_HOLDER_KEY,)
        ).fetchone()
        if not row or row["value"] != holder:
            return
        _set_meta(connection, _SYNC_LOCK_HOLDER_KEY, "")
        _set_meta(connection, _SYNC_LOCK_LABEL_KEY, "")
        _set_meta(connection, _SYNC_LOCK_HEARTBEAT_KEY, "")


def db_sync_lock_status(schema: str = SCHEMA) -> dict[str, str] | None:
    """Read-only check for whether a vendor sync is running somewhere (this
    instance or another) -- used to block Add OS / Refresh EOL/EOAS / starting
    another vendor sync while one is in progress. None if no live lock is held."""
    with _connect(schema) as connection:
        holder = _get_meta(connection, _SYNC_LOCK_HOLDER_KEY, "")
        heartbeat_at = _get_meta(connection, _SYNC_LOCK_HEARTBEAT_KEY, "")
        if not holder or _sync_lock_is_stale(heartbeat_at):
            return None
        return {"label": _get_meta(connection, _SYNC_LOCK_LABEL_KEY, ""), "heartbeat_at": heartbeat_at}


def describe_target() -> str:
    """host:port/dbname parsed from DATABASE_URL, never the password -- safe
    to show in the CLI import output or the app's storage-mode indicator."""
    try:
        info = conninfo_to_dict(get_database_url())
        return f"{info.get('host', '?')}:{info.get('port', '5432')}/{info.get('dbname', '?')}"
    except Exception:
        return "Postgres"


def _read_files_data_source() -> tuple[list[dict[str, str]], dict[str, object]]:
    """Rows + evidence for the "data" source, read directly off the CSV/JSON
    baked into the image at app.DATA_PATH/app.DATA_EVIDENCE_PATH -- this is
    the one-time seed for a brand-new, empty Postgres database, not a
    general-purpose file-mode reader (app.py has no such thing anymore)."""
    import app  # local import -- avoids a circular import when app.py imports this module

    rows = app._read_rows_csv(app.DATA_PATH) if app.DATA_PATH.exists() else []
    evidence = app._load_evidence_file()
    return rows, evidence


def import_from_files_if_empty(schema: str = SCHEMA) -> bool:
    """Auto-import hook, meant to run once on every container/app startup
    (see docker/entrypoint.sh): if this schema's "data" source doesn't
    already have any rows in Postgres, and a local _data/eol_lookup.csv is
    present, load it in -- the same one-time cutover _import_from_files
    below does by hand, just automatic. Always safe to call: a no-op once
    the DB already has data (from a prior import OR a real publish through
    the app), and a no-op on a brand-new deployment with nothing in
    _data/ yet either. Returns whether an import actually happened.

    Always prints exactly one status line, even when it's a no-op --
    otherwise "already has data, skipped" and "this hook never ran at all"
    both look identical in `docker compose logs` (nothing), which makes it
    impossible to tell the entrypoint step actually executed.
    """
    if db_source_exists("data", schema=schema):
        print(f"[lookup_db] Postgres schema '{schema}' already has 'data' rows -- skipping import.")
        return False

    rows, evidence = _read_files_data_source()
    if not rows:
        print(f"[lookup_db] No _data/eol_lookup.csv found (or it's empty) -- nothing to import into '{schema}'.")
        return False

    print(
        f"[lookup_db] No 'data' rows in Postgres schema '{schema}' yet -- "
        f"importing {len(rows)} row(s) from _data/eol_lookup.csv ..."
    )
    db_save_rows(rows, "data", schema=schema)
    db_save_evidence(evidence, "data", schema=schema)
    print(f"[lookup_db] Imported {len(rows)} row(s) into Postgres schema '{schema}'.")
    return True


def _import_from_files(force: bool = False) -> None:
    """Manual, explicit (re-)import: loads the current _data/eol_lookup.csv
    + evidence sidecar into this DB's 'data' source, overwriting whatever
    is already there. Run directly: `python lookup_db.py` (add `--force`
    to proceed even if the DB already has 'data' rows -- otherwise this
    refuses, since it's destructive and the automatic startup hook
    (import_from_files_if_empty, wired into docker/entrypoint.sh) already
    covers the common "first deploy, DB is empty" case without needing
    this script run by hand at all)."""
    import time

    if not force and db_source_exists("data"):
        raise SystemExit(
            "Postgres schema 'lookup' already has 'data' rows -- refusing to "
            "overwrite them. Pass --force if you really want to replace the "
            "DB's current data with _data/eol_lookup.csv."
        )

    target = describe_target()
    print(f"Connecting to {target} ...")
    t0 = time.monotonic()
    try:
        with get_pool().connection() as connection:
            connection.execute("SELECT 1")
    except Exception as exc:
        print(f"Connection failed after {time.monotonic() - t0:.2f}s: {exc}")
        raise
    print(f"Connected in {time.monotonic() - t0:.2f}s.")

    rows, evidence = _read_files_data_source()

    print(f"Importing {len(rows)} row(s) into schema '{SCHEMA}' at {target} ...")

    def report(done: int, total: int) -> None:
        print(f"  {done}/{total} row(s) inserted ({done * 100 // total if total else 100}%)")

    db_save_rows(rows, "data", on_progress=report)
    db_save_evidence(evidence, "data")
    print(f"Imported {len(rows)} row(s) into Postgres schema '{SCHEMA}'.")


if __name__ == "__main__":
    import sys

    _import_from_files(force="--force" in sys.argv[1:])
