apiVersion: v1
kind: ConfigMap
metadata:
  name: os-health-check-config
  namespace: os-health-check
data:
  DEPLOYMENT_ID: "azure-aks-prodtest"
  KEYCLOAK_ISSUER_URL: "https://keycloak.example.com/realms/os-health-check"
  KEYCLOAK_AUDIENCE: "os-health-check-web"
  KEYCLOAK_PUBLISHER_ROLE: "lookup-publisher"
