"""PostgreSQL helpers for vendor lookup caches (one schema per source)."""

from __future__ import annotations

import os
import re
from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

# App source ids → Postgres schema names
SOURCE_SCHEMAS: dict[str, str] = {
    "eosl": "eosl",
    "junos": "junos",
    "suse": "suse",
    "layer23-switch": "layer23_switch",
    "router-switch": "router_switch",
}

_SCHEMA_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_pool: ConnectionPool | None = None
_ensured_schemas: set[str] = set()

_VENDOR_DDL = """
CREATE TABLE IF NOT EXISTS metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'os',
    url TEXT NOT NULL,
    scraped_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_slug TEXT NOT NULL REFERENCES products(slug),
    release_name TEXT NOT NULL,
    released_date TEXT NOT NULL DEFAULT '',
    eol_date TEXT NOT NULL DEFAULT '',
    eoas_date TEXT NOT NULL DEFAULT '',
    latest_raw TEXT NOT NULL DEFAULT '',
    is_supported INTEGER NOT NULL DEFAULT 0,
    UNIQUE (product_slug, release_name)
);

CREATE INDEX IF NOT EXISTS idx_releases_product ON releases (product_slug);
"""


def get_database_url() -> str:
    url = str(os.environ.get("DATABASE_URL") or "").strip()
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. Configure PostgreSQL for vendor lookup caches."
        )
    return url


def schema_for_source(source_id: str, schema_override: str | None = None) -> str:
    if schema_override:
        name = schema_override.strip().lower()
        if not _SCHEMA_NAME_RE.match(name):
            raise ValueError(f"Invalid schema name: {schema_override!r}")
        return name
    key = str(source_id or "").strip().lower()
    if key not in SOURCE_SCHEMAS:
        raise ValueError(f"Unknown vendor source id: {source_id!r}")
    return SOURCE_SCHEMAS[key]


def get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            conninfo=get_database_url(),
            min_size=1,
            max_size=10,
            kwargs={"row_factory": dict_row, "autocommit": False},
            open=True,
        )
    return _pool


def close_pool() -> None:
    global _pool, _ensured_schemas
    if _pool is not None:
        _pool.close()
        _pool = None
    _ensured_schemas.clear()


def ensure_schema(schema: str) -> None:
    """Create schema + vendor tables once per process (idempotent)."""
    name = schema.strip().lower()
    if not _SCHEMA_NAME_RE.match(name):
        raise ValueError(f"Invalid schema name: {schema!r}")
    if name in _ensured_schemas:
        return

    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(
            sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(name))
        )
        connection.execute(
            sql.SQL("SET search_path TO {}, public").format(sql.Identifier(name))
        )
        connection.execute(_VENDOR_DDL)
        connection.commit()
    _ensured_schemas.add(name)


def init_source_schema(source_id: str, schema_override: str | None = None) -> str:
    schema = schema_for_source(source_id, schema_override)
    ensure_schema(schema)
    return schema


@contextmanager
def connection_for(
    source_id: str, *, schema_override: str | None = None
) -> Iterator[psycopg.Connection[Any]]:
    schema = init_source_schema(source_id, schema_override)
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(
            sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema))
        )
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise


def set_metadata(connection: psycopg.Connection[Any], key: str, value: str) -> None:
    connection.execute(
        """
        INSERT INTO metadata (key, value) VALUES (%s, %s)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        """,
        (key, value),
    )


def drop_schema(schema: str) -> None:
    """Drop a schema (used by tests for disposable schemas)."""
    name = schema.strip().lower()
    if not _SCHEMA_NAME_RE.match(name):
        raise ValueError(f"Invalid schema name: {schema!r}")
    pool = get_pool()
    with pool.connection() as connection:
        connection.execute(
            sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(name))
        )
        connection.commit()
    _ensured_schemas.discard(name)
